[package]
name = "ccsds_scppm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ccsds_scppm"

[dependencies]
nalgebra = "0.32.3"
bitvec = "1.0.1"

[dev-dependencies]
rand = "0.8.5"
